language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - touch storage/database.sqlite
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then ./vendor/bin/test-reporter; fi
