language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - mysql -e "create database IF NOT EXISTS tylootest;" -uroot

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source
  - travis_retry php artisan migrate

script:
  - phpunit
