language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - cp .env.example .env
  - touch database/database.sqlite
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source
  - travis_retry php artisan migrate --database="sqlite"

script:
  - phpunit
